//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlytaloEntities : DbContext
    {
        public AlytaloEntities()
            : base("name=AlytaloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Loki> Loki { get; set; }
        public virtual DbSet<Ominaisuudet> Ominaisuudet { get; set; }
        public virtual DbSet<Sauna> Sauna { get; set; }
        public virtual DbSet<Termostaatti> Termostaatti { get; set; }
        public virtual DbSet<Valot> Valot { get; set; }
    }
}
