//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauna
    {
        public int SaunaId { get; set; }
        public Nullable<int> OminaisuusId { get; set; }
        public Nullable<bool> Kaynnissa { get; set; }
        public Nullable<int> Lampo { get; set; }
    
        public virtual Ominaisuudet Ominaisuudet { get; set; }
    }
}
