//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termostaatti
    {
        public int Id { get; set; }
        public Nullable<int> Tavoite { get; set; }
        public Nullable<int> Lampo { get; set; }
    }
}
